// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVVDrhCL8ecCyfe2_5Zg_QaISfdbfM9YU',
    appId: '1:193929570774:web:92ce7a0eeee11dca5f1c77',
    messagingSenderId: '193929570774',
    projectId: 'auth-fire-base-second',
    authDomain: 'auth-fire-base-second.firebaseapp.com',
    storageBucket: 'auth-fire-base-second.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxmafI0XnEopc4p6a7Zi6Eb7hGzZ_46vE',
    appId: '1:193929570774:ios:ebe4a25589a5fb6e5f1c77',
    messagingSenderId: '193929570774',
    projectId: 'auth-fire-base-second',
    storageBucket: 'auth-fire-base-second.appspot.com',
    iosBundleId: 'com.example.secondTry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxmafI0XnEopc4p6a7Zi6Eb7hGzZ_46vE',
    appId: '1:193929570774:ios:ebe4a25589a5fb6e5f1c77',
    messagingSenderId: '193929570774',
    projectId: 'auth-fire-base-second',
    storageBucket: 'auth-fire-base-second.appspot.com',
    iosBundleId: 'com.example.secondTry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVVDrhCL8ecCyfe2_5Zg_QaISfdbfM9YU',
    appId: '1:193929570774:web:0b4232d728d5cf675f1c77',
    messagingSenderId: '193929570774',
    projectId: 'auth-fire-base-second',
    authDomain: 'auth-fire-base-second.firebaseapp.com',
    storageBucket: 'auth-fire-base-second.appspot.com',
  );
}
